import {
  FileSpreadsheet,
  FileCode,
  FileText,
  BookOpen,
  GitCompare,
  Binary,
  Link2,
  ShieldAlert,
  Terminal,
  Lock,
  Layers,
  Clock,
  Search,
  ListTree,
  ShieldCheck,
  Fingerprint,
  Database,
  Key,
  Globe,
  Tag,
} from 'lucide-react';

export const ALL_TOOLS = [
  // Data & Format
  {
    path: '/json-to-csv',
    label: 'JSON to CSV',
    desc: 'Convert JSON to CSV / Excel with nested arrays',
    badge: 'POPULAR',
    icon: FileSpreadsheet,
    category: 'Data',
  },
  {
    path: '/csv-to-json',
    label: 'CSV to JSON',
    desc: 'Parse RFC 4180 CSV tables to structured JSON',
    icon: FileCode,
    category: 'Data',
  },
  {
    path: '/json-viewer',
    label: 'JSON Tree & Query',
    desc: 'Collapsible tree view, JSONPath query & filter',
    badge: 'NEW',
    icon: ListTree,
    category: 'Data',
  },
  {
    path: '/json-to-types',
    label: 'JSON to Types',
    desc: 'Generate TypeScript, Zod, and Go interfaces',
    icon: Layers,
    category: 'Data',
  },
  {
    path: '/base64-tool',
    label: 'Base64 Tool',
    desc: 'Encode, decode strings, files & image hex inspector',
    icon: Binary,
    category: 'Data',
  },

  // Security & Privacy
  {
    path: '/security-headers',
    label: 'Security Headers',
    desc: 'OWASP header evaluator & server config generator',
    badge: 'NEW',
    icon: ShieldCheck,
    category: 'Security',
  },
  {
    path: '/cert-inspector',
    label: 'X.509 Cert & CSR',
    desc: 'Decode SSL certificates, expiration countdown & SANs',
    badge: 'NEW',
    icon: ShieldCheck,
    category: 'Security',
  },
  {
    path: '/cors-analyzer',
    label: 'CORS Policy & Auditor',
    desc: 'Build CORS rules, audit credential leaks & preflight',
    badge: 'NEW',
    icon: Globe,
    category: 'Security',
  },
  {
    path: '/key-generator',
    label: 'RSA & ECC Key Gen',
    desc: 'Generate RSA & ECC key pairs, PEM & JWK in WebCrypto',
    badge: 'NEW',
    icon: Key,
    category: 'Security',
  },
  {
    path: '/sri-generator',
    label: 'SRI Hash & Tags',
    desc: 'Subresource integrity sha384 hashes & CDN HTML tags',
    badge: 'NEW',
    icon: Tag,
    category: 'Security',
  },
  {
    path: '/hash-generator',
    label: 'Hash & Secrets',
    desc: 'SHA-256/512, MD5, HMAC, file checksums & secrets',
    badge: 'NEW',
    icon: Fingerprint,
    category: 'Security',
  },
  {
    path: '/jwt-inspector',
    label: 'JWT Inspector',
    desc: 'Decode tokens, explore claims & verify HMAC signature',
    badge: 'POPULAR',
    icon: Lock,
    category: 'Security',
  },
  {
    path: '/pii-redactor',
    label: 'PII Redactor',
    desc: 'Mask emails, SSNs, credit cards & phone numbers',
    icon: ShieldAlert,
    category: 'Security',
  },

  // Docs & Text
  {
    path: '/markdown-editor',
    label: 'Markdown Editor',
    desc: 'Live dual-pane editor with GitHub flavored syntax',
    icon: FileText,
    category: 'Docs',
  },
  {
    path: '/pdf-to-markdown',
    label: 'PDF Reader',
    desc: 'Extract clean markdown and tables from PDF docs',
    icon: BookOpen,
    category: 'Docs',
  },
  {
    path: '/text-diff',
    label: 'Text Diff',
    desc: 'Side-by-side and unified semantic diff comparison',
    badge: 'POPULAR',
    icon: GitCompare,
    category: 'Docs',
  },

  // Dev & API
  {
    path: '/timestamp-converter',
    label: 'Epoch Timestamp',
    desc: 'Unix epoch converter & 8-city international matrix',
    badge: 'NEW',
    icon: Clock,
    category: 'Dev',
  },
  {
    path: '/sql-formatter',
    label: 'SQL Formatter',
    desc: 'Beautify & minify multi-dialect SQL statements',
    badge: 'NEW',
    icon: Database,
    category: 'Dev',
  },
  {
    path: '/uuid-generator',
    label: 'UUID & ULID',
    desc: 'Batch UUIDv4/v7, ULID, NanoID with timestamp reader',
    badge: 'NEW',
    icon: Binary,
    category: 'Dev',
  },
  {
    path: '/curl-converter',
    label: 'cURL to Code',
    desc: 'Convert cURL commands to 8 client languages',
    icon: Terminal,
    category: 'Dev',
  },
  {
    path: '/url-parser',
    label: 'URL Parser',
    desc: 'Deconstruct URLs, query params and rebuild query strings',
    icon: Link2,
    category: 'Dev',
  },
  {
    path: '/cron-scheduler',
    label: 'Cron Scheduler',
    desc: 'Translate cron expressions to human readable schedule',
    icon: Clock,
    category: 'Dev',
  },
  {
    path: '/regex-tester',
    label: 'Regex Tester',
    desc: 'Test regex patterns with syntax highlighting & tokens',
    icon: Search,
    category: 'Dev',
  },
];
